server:
  port: 8004

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useEncoding=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: 192.168.126.10:2181,192.168.126.10:2182,192.168.126.10:2183

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sun.cloud.bean

