server:
  port: 80

spring:
  application:
    name: order-consumer-80
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采集比例，所设置的值介于 0 到 1 之间，1 则表示全部采集

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
