server:
  port: 80

spring:
  application:
    name: order-consul
  cloud:
    consul:
      host: 192.168.126.10
      port: 8500
      discovery:
        register: false
        heartbeat:
          enabled: true
