server:
  port: 9527

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
        uri: lb://PAYMENT-PROVIDER #匹配后提供服务的路由地址
        predicates:
        - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - After=2020-06-08T19:08:00.042+08:00[Asia/Shanghai]
      - id: payment_routh2
        uri: http://localhost:8002
        predicates:
        - Path=/payment/**
        - After=2020-06-08T19:08:00.042+08:00[Asia/Shanghai]
        filters:
        - AddRequestParameter=color, blue


eureka:
  instance:
    instance-id: gateway-9527
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
