server:
  port: 8001

spring:
  application:
    name: hystrix-payment-service

eureka:
  instance:
    instance-id: hystrix-payment-8001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/