server:
  port: 9001

spring:
  application:
    name: express-provider

eureka:
  instance:
    instance-id: express-9001
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/